### PR TITLE
Update Modularis.js 

### PR DESCRIPTION
**Pull request by adunkey**
fix for huntr command inj 

| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #1234, #5678
| License       | MIT
| Doc PR        | https://github.com/pm2-hive/pm2-hive.github.io/pulls

### CODE REVIEW

**Review by toufik-airane — APPROVED** [review]
LGTM 👏

**Comment by toufik-airane** [comment]
As mention by bl4de in the report https://hackerone.com/reports/630227.
Basic URLs and NPM package names are also vulnerable to command injection.
I think the current fix partially mitigates the issue.

**Review by toufik-airane — COMMENTED** [review]
As mention by bl4de in the report https://hackerone.com/reports/630227.
Basic URLs and NPM package names are also vulnerable to command injection.
I think the current fix partially mitigates the issue.

**Review by toufik-airane — COMMENTED** [review]
As mention by bl4de in the report https://hackerone.com/reports/630227.
Basic URLs and NPM package names are also vulnerable to command injection.
I think the current fix partially mitigates the issue.

**Comment by toufik-airane** [comment]
Sorry for the duplicate message.

**Comment by JamieSlome** [comment]
Thank you for submitting your pull request. On this occasion, one of your fellow huntrs submitted a valid fix before you. We appreciate your effort and look forward to reviewing more of your fixes in the future!

**Pull request closed without merging**
